config/routes.rb
Rails.application.routes.draw do
  
  root 'matches#index'

  namespace :api do
    namespace :v1 do
      post 'matches', to: 'matches#create'
    end
  end

  resources :matches, only: [:new, :index]
  resources :clips, only: [:create, :index, :new, :show]

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clip.rb
class Clip < ApplicationRecord
	has_attached_file :file
  validates_attachment_content_type :file, content_type: /\Aaudio/

  def self.sample(n)
    count.times.to_a.sample(n).map do |offset|
      offset(offset).limit(1).first
    end
  end
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :winner, class_name: "Clip"
  belongs_to :loser, class_name: "Clip"
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :matches
end

app/controllers/api/v1/api_controller.rb
class Api::V1::ApiController < ApplicationController
  # protect_from_forgery with: :null_session
end

app/controllers/api/v1/matches_controller.rb
class Api::V1::MatchesController < Api::V1::ApiController
  skip_before_action :verify_authenticity_token

  def create
    return head :unauthorized unless user_signed_in?
    @match = current_user.matches.new match_params
    raise unless @match.save
    head :no_content
  end

  private
    def match_params
      params.permit(:winner_id, :loser_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/clips_controller.rb
class ClipsController < ApplicationController
  def index
    @clips = Clip.all
  end

  def new
    @clip = Clip.new
  end

  def create
    clip = Clip.new clip_params
    if clip.save
      redirect_to clips_path
    else
      flash[:error] = clip.errors.messages.join
      render :new
    end
  end

  def show
    @clip = Clip.find params[:id]
  end

  private

    def clip_params
      params.require(:clip).permit(:file)
    end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  
  def index
    @matches = Match.all
  end

  def new
    redirect_to new_user_registration_path unless user_signed_in?

    clipA, clipB = Clip.sample 2
    
    @props = {
      clipAUrl: clipA.file.url,
      clipAId: clipA.id,
      clipBUrl: clipB.file.url,
      clipBId: clipB.id,
    }
  end
end

app/helpers/api/v1/matches_helper.rb
module Api::V1::MatchesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clips_helper.rb
module ClipsHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/clips/index.html.erb
<h1>Clips#index</h1>
<p>Find me in app/views/clips/index.html.erb</p>
Clip Count: <%= @clips.count %><br>
<%= link_to "Upload New Clip", new_clip_path %>

app/views/clips/new.html.erb
<h1>Clips#new</h1>

<%= form_for Clip.new, url: {action: "create"} do |f| %>
  <%= f.label :file %>
  <%= f.file_field :file %><br>
  <%= f.submit "Create" %>
<% end %>

app/views/clips/show.html.erb
<h1>Clips#create</h1>

<%= react_component("Player", props: { audioFile: @clip.file.url }) %>

app/views/hello_world/index.html.erb
<h1>Hello World</h1>
<%= react_component("HelloWorld", props: @hello_world_props, prerender: false) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quimming</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_pack_tag 'webpack-bundle' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/layouts/hello_world.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReactOnRailsWithWebpacker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'webpack-bundle' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/matches/index.html.erb
Matches: <%= @matches.count %>
<%= link_to "Start Matching", new_match_path %>

app/views/matches/new.html.erb
<h1>Matches#show</h1>
<%= react_component("Match", props: @props) %>